### ISSUE TITLE
咨询实现思路

### ISSUE THREAD

**Issue by zaihuishou** [yhongm/android-subway#2]
你好，最近我需要做地铁的这种路线的东西，看了你的这个demo感觉不错，想问一些问题。
stationenc.txt　　subwayenc.txt　这个两个文件格式是怎么样的，是怎么生成的？

**Comment by yhongm** [comment]
文件内容保存的就是svg的数据，只不过经过了加密。绘制基本思路就是根据svg把内部的点线解析出来之后绘制view

**Comment by tangxiaopingdev** [comment]
有点击事件吗？

**Comment by yhongm** [comment]
有点击事件

**Comment by tangxiaopingdev** [comment]
> 有点击事件

svg元素的点击的逻辑在哪呢？我没有找到。

**Comment by yhongm** [comment]
RenderSvgPathView 有 setListener 方法监听
