### ISSUE TITLE
地铁图的数据怎么编辑，这是什么编码的？

### ISSUE THREAD

**Issue by dongweiq** [yhongm/android-subway#3]
`            val stationEncBa = JniSm4.assetContentDec(assets, "stationenc.txt")
            val subwayEncBa = JniSm4.assetContentDec(assets, "subwayenc.txt")`

目前用utf8和gbk和gb2312编码打开都是乱码，我想用其他城市的地铁图，但是不知道怎么生成数据

**Comment by yhongm** [comment]
svg格式数据，数据经过sm4算法加密。其他城市你可以自己找对应的svg数据
